# ===================================================================
# Spring Boot configuration for the "secret-samples" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Samples for required secrets to be used in development and ci using prod profile.
# ===================================================================

spring:

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: ZmJkOTkyMjZlMmNlM2I2MmRhMjU3YzkzMWRkODFkZjZmYTZmMTdmZTFhNDFkNTM4Mjk0N2Q1OWNjYjc3MWU0M2ViOTZjNjg0NGUzYmU1MTY5ZTEyODhiODQ4OWZjNjI4YTVhN2QyNDYxNTM4YWY0MmMxZWViMDhlNDRiNzk3ODE=
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    username: tayra
    password:
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    username: tayra
    password:
