#!/usr/bin/env python3
"""
Builds the offline English-to-Russian dictionary used by the app from two kaikki.org dumps:

  * the English section of the Russian Wiktionary (glosses in Russian), e.g.
    dictionaries/english-to-russian.jsonl
  * the English Wiktionary (complete inflection tables), e.g.
    dictionaries/kaikki.org-dictionary-English.jsonl.gz

Only the fields the app needs survive: word, part of speech, Russian glosses with their tags,
an IPA transcription, and a table mapping every inflected form back to its lemma. Forms come
from both dumps; lemmas that neither dump inflects get regular English forms generated by
rule and flagged as such.

Usage: python3 tools/build_english_russian_dictionary.py [--ru FILE] [--en FILE] [--out FILE]
"""
import argparse
import gzip
import json
import re
import sys
from collections import Counter, defaultdict

RU_DEFAULT = "dictionaries/english-to-russian.jsonl"
EN_DEFAULT = "dictionaries/kaikki.org-dictionary-English.jsonl.gz"
OUT_DEFAULT = "dictionaries/english-to-russian.json"

# Entries in the English dump whose "forms" are not inflections but table markup or spellings.
SKIP_FORM_TAGS = {"table-tags", "inflection-template", "canonical", "class", "romanization", "alternative", "misspelling"}
WORD_RE = re.compile(r"^[A-Za-z][A-Za-z'\-]*$")
# A Russian Wiktionary sense that only says "spelling variant of X".
VARIANT_RE = re.compile(r"^вариант (\S+)$")
VOWELS = set("aeiou")


def is_clean_form(form, lemma):
    """Accepts plain words or phrases only; the dumps mark unattested forms with * and add notes in brackets."""
    return form and form != lemma and len(lemma) > 1 and all(WORD_RE.match(part) for part in form.split())


def open_text(path):
    if path.endswith(".gz"):
        return gzip.open(path, "rt", encoding="utf-8")
    return open(path, encoding="utf-8")


def load_russian(path):
    """Returns (entries, forms, variants, dropped) from the Russian Wiktionary dump, dropping senses without glosses."""
    entries = []
    forms = set()
    variants = set()
    dropped = 0
    with open_text(path) as f:
        for line in f:
            d = json.loads(line)
            senses = []
            for s in d.get("senses", []):
                glosses = [g.strip() for g in s.get("glosses", []) if g.strip()]
                if not glosses:
                    continue
                sense = {"glosses": glosses}
                tags = [t for t in s.get("tags", []) if t != "form-of"]
                if tags:
                    sense["tags"] = tags
                # Targets may carry a page anchor such as "log#(глагол_I)".
                form_of = [x["word"].split("#")[0] for x in s.get("form_of", []) if x.get("word")]
                if form_of:
                    sense["formOf"] = form_of
                senses.append(sense)
            if not senses:
                dropped += 1
                continue
            entry = {"word": d["word"], "pos": d["pos"], "senses": senses}
            ipa = next((x["ipa"] for x in d.get("sounds", []) if x.get("ipa")), None)
            if ipa:
                entry["ipa"] = ipa
            entries.append(entry)
            for x in d.get("forms", []):
                form = x.get("form", "").strip()
                # Inflection templates sometimes leave only the suffix here ("ed", "ing", "ping"), so a
                # form must share the lemma's stem; irregulars such as "went" come from the English dump.
                stem = d["word"][: min(3, len(d["word"]) - 1)].lower()
                if is_clean_form(form, d["word"]) and form.lower().startswith(stem):
                    forms.add((form, d["word"]))
            for sense in senses:
                for lemma in sense.get("formOf", []):
                    if is_clean_form(d["word"], lemma):
                        forms.add((d["word"], lemma))
                match = VARIANT_RE.match(sense["glosses"][0]) if len(sense["glosses"]) == 1 else None
                if match:
                    variants.add((d["word"], match.group(1)))
    return entries, forms, variants, dropped


def load_english_forms(path, lemmas, report_every=200_000):
    """Collects (form, lemma) pairs from the English Wiktionary dump for the given lemmas."""
    forms = set()
    seen = 0
    with open_text(path) as f:
        for line in f:
            seen += 1
            if seen % report_every == 0:
                print(f"  scanned {seen:,} English entries, {len(forms):,} forms so far", file=sys.stderr)
            d = json.loads(line)
            word = d.get("word", "")
            if word in lemmas:
                for x in d.get("forms", []):
                    form = x.get("form", "").strip()
                    if set(x.get("tags", [])) & SKIP_FORM_TAGS:
                        continue
                    if is_clean_form(form, word):
                        forms.add((form, word))
            for s in d.get("senses", []):
                for x in s.get("form_of", []):
                    lemma = x.get("word", "")
                    if lemma in lemmas and is_clean_form(word, lemma):
                        forms.add((word, lemma))
    return forms


def double_final(word):
    """Doubles the last consonant of a short consonant-vowel-consonant word (stop, stopped)."""
    if len(word) < 3:
        return False
    a, b, c = word[-3], word[-2], word[-1]
    return c not in VOWELS and c not in "wxy" and b in VOWELS and a not in VOWELS


def regular_forms(word, pos):
    """Regular inflections for a single lowercase word; comparatives are too irregular to guess."""
    if len(word) < 2 or not WORD_RE.match(word) or not word.islower() or "'" in word:
        return []
    out = []
    if pos in ("noun", "verb"):
        if word.endswith(("s", "x", "z", "ch", "sh")):
            out.append(word + "es")
        elif word.endswith("y") and word[-2] not in VOWELS:
            out.append(word[:-1] + "ies")
        else:
            out.append(word + "s")
    if pos == "verb":
        if word.endswith("ie"):
            out.append(word[:-2] + "ying")
        elif word.endswith("e") and not word.endswith(("ee", "ye", "oe")):
            out.append(word[:-1] + "ing")
        elif double_final(word):
            out.append(word + word[-1] + "ing")
        else:
            out.append(word + "ing")
        if word.endswith("e"):
            out.append(word + "d")
        elif word.endswith("y") and word[-2] not in VOWELS:
            out.append(word[:-1] + "ied")
        elif double_final(word):
            out.append(word + word[-1] + "ed")
        else:
            out.append(word + "ed")
    return out


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--ru", default=RU_DEFAULT, help="Russian Wiktionary dump (English section)")
    parser.add_argument("--en", default=EN_DEFAULT, help="English Wiktionary dump, .jsonl or .jsonl.gz")
    parser.add_argument("--out", default=OUT_DEFAULT, help="output JSON file")
    parser.add_argument("--skip-english", action="store_true", help="do not read the English dump (forms from rules only)")
    args = parser.parse_args()

    print(f"Reading {args.ru}", file=sys.stderr)
    entries, forms, variants, dropped = load_russian(args.ru)
    lemmas = {e["word"] for e in entries}
    # Spelling variants point at the main entry and get no guessed inflections of their own.
    forms |= {(word, target) for word, target in variants if target in lemmas}
    variant_words = {word for word, _ in variants}
    lemma_pos = defaultdict(set)
    for e in entries:
        lemma_pos[e["word"]].add(e["pos"])
    print(f"  {len(entries):,} entries kept, {dropped:,} without glosses dropped, {len(forms):,} forms listed", file=sys.stderr)

    ru_forms = len(forms)
    if not args.skip_english:
        print(f"Reading {args.en}", file=sys.stderr)
        forms |= load_english_forms(args.en, lemmas)
        print(f"  {len(forms) - ru_forms:,} forms added from the English Wiktionary", file=sys.stderr)

    inflected = {lemma for _, lemma in forms}
    # A form the dumps already attribute to some lemma is never guessed for another one, so an
    # obsolete spelling such as "playe" cannot claim "played".
    known_forms = {form.lower() for form, _ in forms}
    generated = set()
    for lemma, poses in lemma_pos.items():
        if lemma in inflected or lemma in variant_words:
            continue
        for pos in poses:
            for form in regular_forms(lemma, pos):
                if form.lower() not in known_forms:
                    generated.add((form, lemma))
    forms |= generated
    print(f"  {len(generated):,} forms generated by rule for {len({l for _, l in generated}):,} lemmas", file=sys.stderr)

    form_rows = []
    for form, lemma in sorted(forms, key=lambda x: (x[0].lower(), x[1])):
        row = {"form": form, "lemma": lemma}
        if (form, lemma) in generated:
            row["generated"] = True
        form_rows.append(row)

    entries.sort(key=lambda e: (e["word"].lower(), e["word"], e["pos"]))
    data = {
        "format": 1,
        "sourceLanguage": "en",
        "targetLanguage": "ru",
        "sources": ["Russian Wiktionary via kaikki.org (glosses)", "English Wiktionary via kaikki.org (inflections)"],
        "license": "CC BY-SA 4.0",
        "entries": entries,
        "forms": form_rows,
    }
    with open(args.out, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, separators=(",", ":"))

    per_pos = Counter()
    for lemma, poses in lemma_pos.items():
        for pos in poses:
            per_pos[pos, lemma in inflected or lemma in {l for _, l in generated}] += 1
    print(f"Wrote {args.out}: {len(entries):,} entries, {len(form_rows):,} form rows", file=sys.stderr)
    for pos in ("noun", "verb", "adj"):
        total = per_pos[pos, True] + per_pos[pos, False]
        print(f"  {pos}: {per_pos[pos, True]:,} of {total:,} lemmas have forms", file=sys.stderr)


if __name__ == "__main__":
    main()
