#!/usr/bin/env python3
"""
Builds an offline dictionary pack for the app from kaikki.org dumps.

With --target ru (the default), de, fr, es or pt, glosses come from a language section of the
Russian, German, French, Spanish or Portuguese Wiktionary (e.g. dictionaries/german-to-russian.jsonl,
dictionaries/english-to-german.jsonl) and inflection tables from the English Wiktionary's dump
for that language (e.g. dictionaries/kaikki.org-dictionary-German.jsonl.gz). With --target en,
both glosses and inflections come from the English Wiktionary dump alone.

Only the fields the app needs survive: word, part of speech, glosses with their tags, an IPA
transcription, and a table mapping every inflected form back to its lemma. For English with a
Russian target, lemmas that neither dump inflects get regular forms generated by rule and
flagged as such (other languages inflect too irregularly to guess).

The output is a gzip-compressed SQLite file (.sqlite.gzip, the extension the app bundles it
under) that the app decompresses once and opens read-only on every platform; the uncompressed
.sqlite file is written next to it for inspection with sqlite3:

  meta(key, value)                           format, source/target language, entry count
  entries(id, word, word_lc, pos, ipa, senses) senses is a JSON list of {glosses, tags}
  forms(form_lc, lemma, generated)

Usage: python3 tools/build_dictionary.py --source de [--target ru|en|de] [--glosses FILE] [--en FILE] [--out FILE]
"""
import argparse
import gzip
import json
import os
import re
import shutil
import unicodedata
import sqlite3
import sys
from collections import Counter, defaultdict

# Per source language: the English name, the stem of its Russian/German Wiktionary section files
# (dictionaries/<stem>-to-russian.jsonl, dictionaries/<stem>-to-german.jsonl) and the English
# Wiktionary dump.
SOURCES = {
    "ru": ("Russian", "russian", "dictionaries/kaikki.org-dictionary-Russian.jsonl.gz"),
    "en": ("English", "english", "dictionaries/kaikki.org-dictionary-English.jsonl.gz"),
    "de": ("German", "german", "dictionaries/kaikki.org-dictionary-German.jsonl.gz"),
    "fr": ("French", "french", "dictionaries/kaikki.org-dictionary-French.jsonl.gz"),
    "pt": ("Portuguese", "portuguese", "dictionaries/kaikki.org-dictionary-Portuguese.jsonl.gz"),
    "es": ("Spanish", "spanish", "dictionaries/kaikki.org-dictionary-Spanish.jsonl.gz"),
    "it": ("Italian", "italian", "dictionaries/kaikki.org-dictionary-Italian.jsonl.gz"),
    "uk": ("Ukrainian", "ukrainian", "dictionaries/kaikki.org-dictionary-Ukrainian.jsonl.gz"),
    "la": ("Latin", "latin", "dictionaries/kaikki.org-dictionary-Latin.jsonl.gz"),
    "tr": ("Turkish", "turkish", "dictionaries/kaikki.org-dictionary-Turkish.jsonl.gz"),
    "be": ("Belarusian", "belarusian", "dictionaries/kaikki.org-dictionary-Belarusian.jsonl.gz"),
    "fi": ("Finnish", "finnish", "dictionaries/kaikki.org-dictionary-Finnish.jsonl.gz"),
    "pl": ("Polish", "polish", "dictionaries/kaikki.org-dictionary-Polish.jsonl.gz"),
    "cs": ("Czech", "czech", "dictionaries/kaikki.org-dictionary-Czech.jsonl.gz"),
    "el": ("Greek", "greek", "dictionaries/kaikki.org-dictionary-Greek.jsonl.gz"),
    "nl": ("Dutch", "dutch", "dictionaries/kaikki.org-dictionary-Dutch.jsonl.gz"),
    "sv": ("Swedish", "swedish", "dictionaries/kaikki.org-dictionary-Swedish.jsonl.gz"),
    "hu": ("Hungarian", "hungarian", "dictionaries/kaikki.org-dictionary-Hungarian.jsonl.gz"),
    # The English Wiktionary files Serbian under Serbo-Croatian, with entries in both scripts.
    "sr": ("Serbo-Croatian", "serbian", "dictionaries/kaikki.org-dictionary-SerboCroatian.jsonl.gz"),
    # Croatian shares that Serbo-Croatian dump; Norwegian uses the Bokmål one.
    "lt": ("Lithuanian", "lithuanian", "dictionaries/kaikki.org-dictionary-Lithuanian.jsonl.gz"),
    "bg": ("Bulgarian", "bulgarian", "dictionaries/kaikki.org-dictionary-Bulgarian.jsonl.gz"),
    "lv": ("Latvian", "latvian", "dictionaries/kaikki.org-dictionary-Latvian.jsonl.gz"),
    "ro": ("Romanian", "romanian", "dictionaries/kaikki.org-dictionary-Romanian.jsonl.gz"),
    "da": ("Danish", "danish", "dictionaries/kaikki.org-dictionary-Danish.jsonl.gz"),
    "no": ("Norwegian", "norwegian", "dictionaries/kaikki.org-dictionary-NorwegianBokmal.jsonl.gz"),
    "sk": ("Slovak", "slovak", "dictionaries/kaikki.org-dictionary-Slovak.jsonl.gz"),
    "et": ("Estonian", "estonian", "dictionaries/kaikki.org-dictionary-Estonian.jsonl.gz"),
    "hr": ("Croatian", "croatian", "dictionaries/kaikki.org-dictionary-SerboCroatian.jsonl.gz"),
    "mk": ("Macedonian", "macedonian", "dictionaries/kaikki.org-dictionary-Macedonian.jsonl.gz"),
    "sl": ("Slovene", "slovene", "dictionaries/kaikki.org-dictionary-Slovene.jsonl.gz"),
    "is": ("Icelandic", "icelandic", "dictionaries/kaikki.org-dictionary-Icelandic.jsonl.gz"),
    "ca": ("Catalan", "catalan", "dictionaries/kaikki.org-dictionary-Catalan.jsonl.gz"),
    "gl": ("Galician", "galician", "dictionaries/kaikki.org-dictionary-Galician.jsonl.gz"),
}
# Gloss languages that come from their own Wiktionary: the dump file suffix and the pattern of
# a sense that only says "variant of X".
TARGETS = {
    "ru": ("Russian Wiktionary", "russian", re.compile(r"^вариант (\S+)$")),
    "de": ("German Wiktionary", "german", re.compile(r"^(?:Nebenform|Schreibvariante|Variante|alternative Schreibweise) (?:von|zu) (\S+)$")),
    "fr": ("French Wiktionary", "french", re.compile(r"^Variante (?:orthographique )?(?:de|d’|d') ?(\S+)\.?$")),
    "es": ("Spanish Wiktionary", "spanish", re.compile(r"^(?:Variante|Grafía (?:alternativa|obsoleta|anticuada)|Forma alternativa) de (\S+)\.?$")),
    "pt": ("Portuguese Wiktionary", "portuguese", re.compile(r"^(?:Variante|Grafia (?:alternativa|antiga|arcaica)|Forma alternativa|Ortografia (?:alternativa|antiga)) de (\S+)\.?$")),
}
# Stored as PRAGMA user_version and in meta; the app checks it before trusting a file.
FORMAT = 1

# Entries in the English dump whose "forms" are not inflections but table markup or spellings.
SKIP_FORM_TAGS = {"table-tags", "inflection-template", "canonical", "class", "romanization", "alternative", "misspelling"}
# Finnish and Hungarian tables also list every possessive-suffix variant of every case, which
# multiplies the pack several times over; those forms are left out to keep it downloadable.
SKIP_FORM_TAGS_BY_SOURCE = {
    "fi": {"possessive", "singular-possessive", "plural-possessive"},
    "hu": {"possessive", "possessed-single", "possessed-many", "error-unrecognized-form"},
}
# A prose "form of X" gloss: the lemma is the last word, possibly after "(to)".
PROSE_FORM_RE = re.compile(r"\b(?:de|del|do|da|of|von|von dem)\s+(?:\(to\)\s+)?([^\s()]+?)[.。]?$")
# A gloss that is nothing but such a description, even without a form-of tag ("plural de muchacho").
FORM_DESCRIPTION_RE = re.compile(
    r"^(?:forma|plural|singular|feminino|femenino|masculino|diminutivo|aumentativo|particípio|participio|gerúndio|gerundio"
    r"|pretérito|presente|futuro|imperativo|infinitivo|primeira|segunda|terceira|primera|tercera|pasado|форма)\b",
    re.IGNORECASE,
)

# Letters in any script, then letters, apostrophes or hyphens.
WORD_RE = re.compile(r"^[^\W\d_](?:[^\W\d_]|['\-])*$")
VOWELS = set("aeiou")


def is_clean_form(form, lemma):
    """
    Accepts plain words, or phrases only for phrase lemmas: the app looks up single tokens, so
    compound forms such as "würde gehen" would never match. The dumps also mark unattested
    forms with * and add notes in brackets, which the word pattern rejects.
    """
    if not form or form == lemma or len(lemma) <= 1:
        return False
    if " " in form and " " not in lemma:
        return False
    return all(WORD_RE.match(part) for part in form.split())


# Umlauts, ß and accents change under inflection ("Haus", "Häuser"; "acheter", "achète";
# "pôr", "ponho"), so stems are compared without them.
UMLAUTS = str.maketrans({
    "ä": "a", "ö": "o", "ü": "u", "ß": "ss",
    "á": "a", "à": "a", "â": "a", "ã": "a", "é": "e", "è": "e", "ê": "e", "í": "i", "î": "i",
    "ó": "o", "ô": "o", "õ": "o", "ò": "o", "ú": "u", "û": "u", "ù": "u", "ü": "u", "ì": "i", "ç": "c", "ñ": "n",
    "č": "c", "ć": "c", "đ": "d", "š": "s", "ž": "z",
    "ł": "l", "ą": "a", "ę": "e", "ś": "s", "ź": "z", "ż": "z", "ń": "n",
    "ě": "e", "ř": "r", "ů": "u", "ý": "y", "ď": "d", "ť": "t", "ň": "n",
    "å": "a", "ő": "o", "ű": "u",
    "ą": "a", "ė": "e", "į": "i", "ų": "u", "ū": "u", "ā": "a", "ē": "e", "ī": "i", "ģ": "g", "ķ": "k", "ļ": "l", "ņ": "n",
    "ă": "a", "ș": "s", "ț": "t", "ş": "s", "ţ": "t", "ø": "o", "æ": "ae", "ð": "d", "þ": "th", "ĺ": "l", "ŕ": "r", "ľ": "l",
})


def plain(word):
    return word.lower().translate(UMLAUTS)


# The Wiktionaries write Serbo-Croatian with pitch accents ("пси̏", "pȁs") and Ukrainian,
# Belarusian, Bulgarian and Macedonian with stress marks ("ха́та") that ordinary text never carries; these combining marks are removed
# so forms match written words.
PITCH_MARKS = {"\u0300", "\u0301", "\u0304", "\u030f", "\u0311", "\u0342"}


PITCH_BEARERS = set("aeiourAEIOURаеиоуряюєіїёэыАЕИОУРЯЮЄІЇЁЭЫ")

# Latin dictionaries mark vowel length with macrons and breves ("puellā", "ămō"); texts do not.
LENGTH_MARKS = {"\u0304", "\u0306"}
LATIN_VOWELS = set("aeiouyAEIOUY")


def strip_length(word):
    out = []
    for c in unicodedata.normalize("NFD", word):
        if c in LENGTH_MARKS and out and out[-1] in LATIN_VOWELS:
            continue
        out.append(c)
    return unicodedata.normalize("NFC", "".join(out))



def strip_pitch(word):
    """Removes pitch marks from vowels and syllabic r; the acute in "ć" is a letter and stays."""
    out = []
    for c in unicodedata.normalize("NFD", word):
        if c in PITCH_MARKS:
            # The base letter may sit behind other marks, e.g. the diaeresis of "ї".
            base = next((b for b in reversed(out) if not unicodedata.combining(b)), "")
            if base in PITCH_BEARERS:
                continue
        out.append(c)
    return unicodedata.normalize("NFC", "".join(out))


# Serbian Latin to Cyrillic. The English Wiktionary keeps the inflection tables on its
# Latin-script entries, while the Russian Wiktionary writes Serbian in Cyrillic.
SERBIAN_DIGRAPHS = {"lj": "љ", "nj": "њ", "dž": "џ"}
SERBIAN_LETTERS = dict(zip("abcčćdđefghijklmnoprsštuvzžywq", "абцчћдђефгхијклмнопрсштувзживк")) | {"x": "кс"}


def to_serbian_cyrillic(word):
    out = []
    lower = word.lower()
    i = 0
    while i < len(word):
        pair = lower[i : i + 2]
        if pair in SERBIAN_DIGRAPHS:
            letter = SERBIAN_DIGRAPHS[pair]
            out.append(letter.upper() if word[i].isupper() else letter)
            i += 2
            continue
        c = word[i]
        mapped = SERBIAN_LETTERS.get(c.lower(), c)
        out.append(mapped.upper() if c.isupper() else mapped)
        i += 1
    return "".join(out)


def serbian_spellings(word):
    """
    A word without pitch accents, in its own script and in Cyrillic. The Russian Wiktionary
    lists most Serbian headwords in Cyrillic but some in Latin, and texts come in either
    script, so every form is stored both ways.
    """
    stripped = clean_serbian_cyrillic(word)
    cyrillic = to_serbian_cyrillic(stripped)
    return [stripped] if cyrillic == stripped else [stripped, cyrillic]


def clean_serbian_cyrillic(word):
    """
    Strips pitch marks and repairs Cyrillic words the dump wrote with precomposed Latin accented
    vowels ("псȁ" is "пс" plus Latin "ȁ"), which would otherwise keep a Latin letter.
    """
    stripped = strip_pitch(word)
    if any("\u0400" <= c <= "\u04ff" for c in stripped):
        return to_serbian_cyrillic(stripped)
    return stripped


# How each source's spellings are normalised before matching, when it needs it at all.
CLEANERS = {"sr": clean_serbian_cyrillic, "uk": strip_pitch, "be": strip_pitch, "ru": strip_pitch, "bg": strip_pitch, "mk": strip_pitch, "hr": strip_pitch, "la": strip_length}


def lowercase(word, source):
    """Turkish has a dotted and a dotless i, so "I" lowers to "ı" and "İ" to "i"; the app does the same."""
    if source == "tr":
        word = word.replace("I", "ı").replace("İ", "i")
    return word.lower()


def open_text(path):
    if path.endswith(".gz"):
        return gzip.open(path, "rt", encoding="utf-8")
    return open(path, encoding="utf-8")


def load_glossary(path, variant_re, clean=lambda word: word):
    """
    Returns (entries, forms, variants, dropped) from a Russian or German Wiktionary section. A
    sense that only says "form of X" or "variant of X" becomes a pointer to X rather than a
    gloss, so the app shows X's meaning and links the term to it; entries left without glosses
    are dropped.
    """
    entries = []
    forms = set()
    variants = set()
    dropped = 0
    with open_text(path) as f:
        for line in f:
            d = json.loads(line)
            senses = []
            entry_is_form = "form-of" in d.get("tags", [])
            for s in d.get("senses", []):
                glosses = [g.strip() for g in s.get("glosses", []) if g.strip()]
                # Targets may carry a page anchor such as "log#(глагол_I)".
                form_of = [x["word"].split("#")[0] for x in s.get("form_of", []) if x.get("word")]
                # Nested senses put the description first ("plural de muchacho", "rapazes, jovens").
                described = glosses and FORM_DESCRIPTION_RE.match(glosses[0])
                if not form_of and glosses and (entry_is_form or "form-of" in s.get("tags", []) or described):
                    # The Spanish and Portuguese Wiktionaries often describe a form in prose that
                    # ends with the lemma: "Tercera persona del singular ... del verbo (to) house."
                    match = PROSE_FORM_RE.search(glosses[0])
                    form_of = [match.group(1)] if match else []
                    if not form_of:
                        continue
                for lemma in form_of:
                    if is_clean_form(d["word"], lemma):
                        forms.add((d["word"], lemma))
                if form_of or not glosses:
                    continue
                match = variant_re.match(glosses[0]) if len(glosses) == 1 else None
                if match:
                    variants.add((d["word"], match.group(1)))
                    continue
                sense = {"glosses": glosses}
                tags = s.get("tags", [])
                if tags:
                    sense["tags"] = tags
                senses.append(sense)
            if not senses:
                dropped += 1
                continue
            entry = {"word": d["word"], "pos": d["pos"], "senses": senses}
            ipa = next((x["ipa"] for x in d.get("sounds", []) if x.get("ipa")), None)
            if ipa:
                entry["ipa"] = ipa
            entries.append(entry)
            for x in d.get("forms", []):
                form = clean(x.get("form", "").strip())
                # Inflection templates sometimes leave only the suffix here ("ed", "ing", "ping"), so a
                # form must share the lemma's stem; irregulars such as "went" come from the English dump.
                stem = plain(d["word"])[: min(3, len(d["word"]) - 1)]
                if is_clean_form(form, d["word"]) and plain(form).startswith(stem):
                    forms.add((form, d["word"]))
    return entries, forms, variants, dropped


def load_english_forms(path, lemmas, spellings=lambda word: [word], skip_tags=SKIP_FORM_TAGS, report_every=200_000):
    """
    Collects (form, lemma) pairs from the English Wiktionary dump for the given lemmas.
    [spellings] lists the spellings a word may be stored under; a headword matches a lemma
    under any of them, and its forms are recorded under all of theirs.
    """
    forms = set()
    seen = 0
    with open_text(path) as f:
        for line in f:
            seen += 1
            if seen % report_every == 0:
                print(f"  scanned {seen:,} English entries, {len(forms):,} forms so far", file=sys.stderr)
            d = json.loads(line)
            raw_word = d.get("word", "")
            for word in spellings(raw_word):
                if word not in lemmas:
                    continue
                for x in d.get("forms", []):
                    if set(x.get("tags", [])) & skip_tags:
                        continue
                    for form in spellings(x.get("form", "").strip()):
                        if is_clean_form(form, word):
                            forms.add((form, word))
            for s in d.get("senses", []):
                for x in s.get("form_of", []):
                    for lemma in spellings(x.get("word", "")):
                        if lemma not in lemmas:
                            continue
                        for word in spellings(raw_word):
                            if is_clean_form(word, lemma):
                                forms.add((word, lemma))
    return forms


def double_final(word):
    """Doubles the last consonant of a short consonant-vowel-consonant word (stop, stopped)."""
    if len(word) < 3:
        return False
    a, b, c = word[-3], word[-2], word[-1]
    return c not in VOWELS and c not in "wxy" and b in VOWELS and a not in VOWELS


def regular_forms(word, pos):
    """Regular inflections for a single lowercase word; comparatives are too irregular to guess."""
    if len(word) < 2 or not WORD_RE.match(word) or not word.islower() or "'" in word:
        return []
    out = []
    if pos in ("noun", "verb"):
        if word.endswith(("s", "x", "z", "ch", "sh")):
            out.append(word + "es")
        elif word.endswith("y") and word[-2] not in VOWELS:
            out.append(word[:-1] + "ies")
        else:
            out.append(word + "s")
    if pos == "verb":
        if word.endswith("ie"):
            out.append(word[:-2] + "ying")
        elif word.endswith("e") and not word.endswith(("ee", "ye", "oe")):
            out.append(word[:-1] + "ing")
        elif double_final(word):
            out.append(word + word[-1] + "ing")
        else:
            out.append(word + "ing")
        if word.endswith("e"):
            out.append(word + "d")
        elif word.endswith("y") and word[-2] not in VOWELS:
            out.append(word[:-1] + "ied")
        elif double_final(word):
            out.append(word + word[-1] + "ed")
        else:
            out.append(word + "ed")
    return out


SCHEMA = """
    CREATE TABLE meta (key TEXT NOT NULL PRIMARY KEY, value TEXT NOT NULL);
    CREATE TABLE entries (
        id INTEGER NOT NULL PRIMARY KEY,
        word TEXT NOT NULL,
        word_lc TEXT NOT NULL,
        pos TEXT NOT NULL,
        ipa TEXT,
        senses TEXT NOT NULL
    );
    CREATE TABLE forms (
        form_lc TEXT NOT NULL,
        lemma TEXT NOT NULL,
        generated INTEGER NOT NULL DEFAULT 0
    );
"""


def open_output(out_path):
    """Creates the SQLite file for a pack; returns (connection, sqlite path)."""
    path = out_path[: -len(".gzip")] if out_path.endswith(".gzip") else out_path + ".sqlite"
    if os.path.exists(path):
        os.remove(path)
    db = sqlite3.connect(path)
    db.executescript(SCHEMA)
    return db, path


def finish_output(db, path, out_path, source, target, entry_count, form_count, sources):
    db.executemany(
        "INSERT INTO meta(key, value) VALUES (?, ?)",
        [
            ("format", str(FORMAT)),
            ("source_language", source),
            ("target_language", target),
            ("entry_count", str(entry_count)),
            ("form_count", str(form_count)),
            ("sources", sources),
            ("license", "CC BY-SA 4.0"),
        ],
    )
    db.executescript(
        f"""
        CREATE INDEX IF NOT EXISTS entries_word_lc ON entries(word_lc);
        CREATE INDEX IF NOT EXISTS forms_form_lc ON forms(form_lc);
        PRAGMA user_version = {FORMAT};
        """
    )
    db.commit()
    db.execute("VACUUM")
    db.close()
    with open(path, "rb") as plain, gzip.open(out_path, "wb", compresslevel=9) as packed:
        shutil.copyfileobj(plain, packed)


def write_sqlite(out_path, entries, form_rows, source, target):
    db, path = open_output(out_path)
    db.executemany(
        "INSERT INTO entries(id, word, word_lc, pos, ipa, senses) VALUES (?, ?, ?, ?, ?, ?)",
        (
            (i + 1, e["word"], lowercase(e["word"], source), e["pos"], e.get("ipa"), json.dumps(e["senses"], ensure_ascii=False, separators=(",", ":")))
            for i, e in enumerate(entries)
        ),
    )
    db.executemany("INSERT INTO forms(form_lc, lemma, generated) VALUES (?, ?, ?)", ((f, l, 1 if g else 0) for f, l, g in form_rows))
    finish_output(
        db, path, out_path, source, target, len(entries), len(form_rows),
        f"{TARGETS[target][0]} via kaikki.org (glosses); English Wiktionary {SOURCES[source][0]} entries via kaikki.org (inflections)",
    )


# Sense tags that only repeat the part of speech or table markup rather than describe usage.
NOISE_SENSE_TAGS = {"form-of", "alt-of", "no-gloss", "morpheme", "romanization"}


def build_english_target(source, en_path, out_path, report_every=200_000):
    """
    Builds a pack whose glosses are the English Wiktionary's own definitions. Entries and forms
    stream straight into SQLite, since the larger dumps hold millions of forms.
    """
    cleaner = CLEANERS.get(source, lambda word: word)
    skip_tags = SKIP_FORM_TAGS | SKIP_FORM_TAGS_BY_SOURCE.get(source, set())
    latin_only = source == "hr"
    db, path = open_output(out_path)
    db.execute("CREATE UNIQUE INDEX forms_unique ON forms(form_lc, lemma)")
    entry_rows, form_rows, seen, next_id = [], [], 0, 1
    entry_count = form_count = pointer_count = 0
    pos_totals, pos_inflected = Counter(), set()

    def flush():
        nonlocal entry_rows, form_rows, form_count
        db.executemany("INSERT INTO entries(id, word, word_lc, pos, ipa, senses) VALUES (?, ?, ?, ?, ?, ?)", entry_rows)
        before = db.total_changes
        db.executemany("INSERT OR IGNORE INTO forms(form_lc, lemma, generated) VALUES (?, ?, 0)", form_rows)
        form_count += db.total_changes - before
        entry_rows, form_rows = [], []

    def cyrillic(text):
        return any("\u0400" <= c <= "\u04ff" for c in text)

    print(f"Reading {en_path}", file=sys.stderr)
    with open_text(en_path) as f:
        for line in f:
            seen += 1
            if seen % report_every == 0:
                print(f"  scanned {seen:,} entries, kept {entry_count:,} with {form_count + len(form_rows):,} forms", file=sys.stderr)
            d = json.loads(line)
            word = cleaner(d.get("word", "").strip())
            if not word or (latin_only and cyrillic(word)):
                continue
            senses = []
            for s in d.get("senses", []):
                tags = s.get("tags", [])
                targets = [cleaner(x["word"]) for x in s.get("form_of", []) + s.get("alt_of", []) if x.get("word")]
                for lemma in targets:
                    if is_clean_form(word, lemma) and not (latin_only and cyrillic(lemma)):
                        form_rows.append((lowercase(word, source), lemma))
                        pointer_count += 1
                if targets or "form-of" in tags or "alt-of" in tags:
                    continue
                glosses = [g.strip() for g in s.get("glosses", []) if g.strip()]
                if not glosses:
                    continue
                # Nested senses list their parent gloss first; the last entry is the sense itself.
                sense = {"glosses": [glosses[-1]]}
                kept_tags = [t for t in tags if t not in NOISE_SENSE_TAGS]
                if kept_tags:
                    sense["tags"] = kept_tags
                senses.append(sense)
            if not senses:
                continue
            pos = d.get("pos") or "unknown"
            ipa = next((x["ipa"] for x in d.get("sounds", []) if x.get("ipa")), None)
            entry_rows.append((next_id, word, lowercase(word, source), pos, ipa, json.dumps(senses, ensure_ascii=False, separators=(",", ":"))))
            next_id += 1
            entry_count += 1
            pos_totals[pos] += 1
            stem = plain(word)[: min(3, len(word) - 1)]
            for x in d.get("forms", []):
                if set(x.get("tags", [])) & skip_tags:
                    continue
                form = cleaner(x.get("form", "").strip())
                if not is_clean_form(form, word) or (latin_only and cyrillic(form)):
                    continue
                form_rows.append((lowercase(form, source), word))
                pos_inflected.add((pos, word))
            if len(entry_rows) >= 5000 or len(form_rows) >= 50000:
                flush()
    flush()
    db.execute("DROP INDEX forms_unique")
    finish_output(
        db, path, out_path, source, "en", entry_count, form_count,
        f"English Wiktionary {SOURCES[source][0]} entries via kaikki.org",
    )
    print(f"Wrote {out_path}: {entry_count:,} entries, {form_count:,} form rows ({pointer_count:,} from form-of senses)", file=sys.stderr)
    inflected_by_pos = Counter(pos for pos, _ in pos_inflected)
    for pos in ("noun", "verb", "adj"):
        print(f"  {pos}: {inflected_by_pos[pos]:,} of {pos_totals[pos]:,} entries have forms", file=sys.stderr)


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--source", choices=sorted(SOURCES), default="en", help="language the pack explains (ISO 639-1)")
    parser.add_argument("--target", choices=["ru", "en", "de", "fr", "es", "pt"], default="ru", help="language the glosses are in")
    parser.add_argument("--glosses", help="Russian or German Wiktionary dump for the source language's section")
    parser.add_argument("--en", help="English Wiktionary dump for the source language, .jsonl or .jsonl.gz")
    parser.add_argument("--out", help="output gzip-compressed SQLite file (default dictionaries/<source>-ru.sqlite.gzip)")
    parser.add_argument("--skip-english", action="store_true", help="do not read the English Wiktionary dump")
    args = parser.parse_args()
    _, file_stem, en_default = SOURCES[args.source]
    args.en = args.en or en_default
    args.out = args.out or f"dictionaries/{args.source}-{args.target}.sqlite.gzip"

    if args.target == "en":
        build_english_target(args.source, args.en, args.out)
        return
    wiktionary, suffix, variant_re = TARGETS[args.target]
    args.glosses = args.glosses or (f"dictionaries/{file_stem}-to-{suffix}.jsonl" if file_stem else None)
    if args.glosses is None or not os.path.exists(args.glosses):
        parser.error(f"no {wiktionary} section for {args.source} at {args.glosses}")

    print(f"Reading {args.glosses}", file=sys.stderr)
    cleaner = CLEANERS.get(args.source, lambda word: word)
    entries, forms, variants, dropped = load_glossary(args.glosses, variant_re, clean=cleaner)
    lemmas = {e["word"] for e in entries}
    # Spelling variants point at the main entry and get no guessed inflections of their own.
    forms |= {(word, target) for word, target in variants if target in lemmas}
    variant_words = {word for word, _ in variants}
    lemma_pos = defaultdict(set)
    for e in entries:
        lemma_pos[e["word"]].add(e["pos"])
    print(f"  {len(entries):,} entries kept, {dropped:,} form-only or gloss-less entries dropped, {len(forms):,} forms listed", file=sys.stderr)

    ru_forms = len(forms)
    if not args.skip_english:
        print(f"Reading {args.en}", file=sys.stderr)
        spellings = serbian_spellings if args.source == "sr" else (lambda word: [cleaner(word)])
        skip_tags = SKIP_FORM_TAGS | SKIP_FORM_TAGS_BY_SOURCE.get(args.source, set())
        forms |= load_english_forms(args.en, lemmas, spellings=spellings, skip_tags=skip_tags)
        print(f"  {len(forms) - ru_forms:,} forms added from the English Wiktionary", file=sys.stderr)

    if args.source == "hr":
        # The Serbo-Croatian tables list every form in both scripts; Croatian is written in Latin.
        forms = {(form, lemma) for form, lemma in forms if not any("\u0400" <= c <= "\u04ff" for c in form)}

    inflected = {lemma for _, lemma in forms}
    # A form the dumps already attribute to some lemma is never guessed for another one, so an
    # obsolete spelling such as "playe" cannot claim "played". Only English is regular enough.
    known_forms = {form.lower() for form, _ in forms}
    generated = set()
    if args.source == "en":
        for lemma, poses in lemma_pos.items():
            if lemma in inflected or lemma in variant_words:
                continue
            for pos in poses:
                for form in regular_forms(lemma, pos):
                    if form.lower() not in known_forms:
                        generated.add((form, lemma))
    forms |= generated
    print(f"  {len(generated):,} forms generated by rule for {len({l for _, l in generated}):,} lemmas", file=sys.stderr)

    form_rows = sorted(
        {(lowercase(form, args.source), lemma, (form, lemma) in generated) for form, lemma in forms},
        key=lambda x: (x[0], x[1]),
    )
    entries.sort(key=lambda e: (e["word"].lower(), e["word"], e["pos"]))
    write_sqlite(args.out, entries, form_rows, args.source, args.target)

    per_pos = Counter()
    for lemma, poses in lemma_pos.items():
        for pos in poses:
            per_pos[pos, lemma in inflected or lemma in {l for _, l in generated}] += 1
    print(f"Wrote {args.out}: {len(entries):,} entries, {len(form_rows):,} form rows", file=sys.stderr)
    for pos in ("noun", "verb", "adj"):
        total = per_pos[pos, True] + per_pos[pos, False]
        print(f"  {pos}: {per_pos[pos, True]:,} of {total:,} lemmas have forms", file=sys.stderr)


if __name__ == "__main__":
    main()
