#!/usr/bin/env python3
"""Generates SherpaPiperVoices.kt: the Piper voices sherpa-onnx packages for phones.

The voices are the assets of the sherpa-onnx "tts-models" release (the compact int8 copies),
read with the GitHub CLI. Language and country names come from the Piper catalog, matched by
locale, so the app needs no locale tables of its own.

    python3 tools/generate_sherpa_voices.py
"""
import json
import pathlib
import subprocess

OUT = pathlib.Path(__file__).resolve().parent.parent / "core/data/src/commonMain/kotlin/com/tayra/languages/core/data/speech/SherpaPiperVoices.kt"
PREFIX, SUFFIX = "vits-piper-", "-int8.tar.bz2"
CATALOG = "https://huggingface.co/rhasspy/piper-voices/resolve/main/voices.json"

raw = subprocess.run(
    ["gh", "api", "repos/k2-fsa/sherpa-onnx/releases/tags/tts-models", "--paginate", "--jq", ".assets[] | [.name, .size] | @tsv"],
    check=True, capture_output=True, text=True,
).stdout
# curl rather than urllib: python.org builds of Python ship without CA certificates.
catalog = json.loads(subprocess.run(["curl", "-sSfL", CATALOG], check=True, capture_output=True, text=True).stdout)
names = {}
for voice in catalog.values():
    lang = voice["language"]
    names[lang["code"]] = (lang["name_english"], lang["country_english"])

voices = []
for line in raw.splitlines():
    name, size = line.split("\t")
    if not (name.startswith(PREFIX) and name.endswith(SUFFIX)):
        continue
    key = name[len(PREFIX):-len(SUFFIX)]
    locale = key.split("-")[0]
    language, country = names.get(locale, (locale, locale.split("_")[-1]))
    voices.append((key, int(size), language, country))
voices.sort()


def q(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


rows = "\n".join(f"        SherpaPiperVoice({q(k)}, {s}L, {q(l)}, {q(c)})," for k, s, l, c in voices)
OUT.parent.mkdir(parents=True, exist_ok=True)
OUT.write_text(f'''package com.tayra.languages.core.data.speech

/** One Piper voice as sherpa-onnx packages it: its `locale-voice-quality` key and download size. */
data class SherpaPiperVoice(val key: String, val sizeBytes: Long, val language: String, val country: String)

/** Generated by tools/generate_sherpa_voices.py; do not edit by hand. */
internal object SherpaPiperVoices {{
    val ALL: List<SherpaPiperVoice> = listOf(
{rows}
    )
}}
''')
print(f"{len(voices)} voices written to {OUT}")
