#!/usr/bin/env python3
"""
Generates core/domain/.../language/Tutorials.kt from tools/tutorial/<code>.txt: the sample book
every language comes with, a tutorial on learning the language with the app, written in it.

Each file holds the book's title on its first line, a blank line, then the text, paragraphs
separated by blank lines. tools/tutorial/en.txt is the source the others translate.

Usage: python3 tools/generate_tutorials.py
"""
import glob
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SOURCES = os.path.join(ROOT, "tools", "tutorial")
OUT = os.path.join(ROOT, "core/domain/src/commonMain/kotlin/com/tayra/languages/core/domain/language/Tutorials.kt")


def raw(s):
    """A Kotlin raw string literal."""
    return '"""' + s.replace("$", "${'$'}").replace('"""', "${'\"'}${'\"'}${'\"'}") + '"""'


def quoted(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"').replace("$", "\\$") + '"'


def read(path):
    with open(path, encoding="utf-8") as f:
        title, _, body = f.read().strip().partition("\n")
    paragraphs = [" ".join(p.split()) for p in body.strip().split("\n\n") if p.strip()]
    return title.strip(), "\n\n".join(paragraphs)


def main():
    tutorials = {os.path.splitext(os.path.basename(p))[0]: read(p) for p in sorted(glob.glob(os.path.join(SOURCES, "*.txt")))}
    lines = [
        "package com.tayra.languages.core.domain.language",
        "",
        "// Generated by tools/generate_tutorials.py from tools/tutorial/*.txt. Do not edit by hand.",
        "",
        "/** The sample book every language comes with: how to learn the language with the app, written in it. */",
        '@Suppress("LargeClass", "MaxLineLength")',
        "object Tutorials {",
        "    data class Tutorial(val title: String, val text: String)",
        "",
        "    /** By ISO 639-1 code. */",
        "    private val byCode: Map<String, Tutorial> by lazy {",
        "        mapOf(",
    ]
    for code, (title, text) in tutorials.items():
        lines.append(f"            {quoted(code)} to Tutorial(")
        lines.append(f"                title = {quoted(title)},")
        lines.append(f"                text = {raw(text)},")
        lines.append("            ),")
    lines += [
        "        )",
        "    }",
        "",
        "    /** The tutorial in the language named [languageName], as the catalog names it. */",
        "    fun forLanguage(languageName: String): Tutorial? = LanguageCodes.codeFor(languageName)?.let { byCode[it] }",
        "}",
        "",
    ]
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"wrote {os.path.relpath(OUT, ROOT)}: {len(tutorials)} languages")


if __name__ == "__main__":
    main()
