#!/usr/bin/env python3
"""Generates SherpaPiperVoices.kt: the Piper voices sherpa-onnx packages for phones.

The list comes from the assets of the sherpa-onnx "tts-models" release (the compact int8
copies), read with the GitHub CLI:  python3 tools/generate_sherpa_voices.py
"""
import json
import pathlib
import subprocess

OUT = pathlib.Path(__file__).resolve().parent.parent / "core/data/src/androidMain/kotlin/com/tayra/languages/core/data/speech/SherpaPiperVoices.kt"
PREFIX, SUFFIX = "vits-piper-", "-int8.tar.bz2"

raw = subprocess.run(
    ["gh", "api", "repos/k2-fsa/sherpa-onnx/releases/tags/tts-models", "--paginate", "--jq", ".assets[] | [.name, .size] | @tsv"],
    check=True, capture_output=True, text=True,
).stdout
voices = []
for line in raw.splitlines():
    name, size = line.split("\t")
    if name.startswith(PREFIX) and name.endswith(SUFFIX):
        voices.append((name[len(PREFIX):-len(SUFFIX)], int(size)))
voices.sort()

rows = "\n".join(f'        "{key}" to {size}L,' for key, size in voices)
OUT.write_text(f'''package com.tayra.languages.core.data.speech

/**
 * The Piper voices sherpa-onnx packages, by `locale-voice-quality` key, with the size of the
 * compact download. Generated by tools/generate_sherpa_voices.py; do not edit by hand.
 */
internal object SherpaPiperVoices {{
    val ALL: List<Pair<String, Long>> = listOf(
{rows}
    )
}}
''')
print(f"{len(voices)} voices written to {OUT}")
