#!/usr/bin/env python3
"""
Generates core/domain/.../language/PredefinedLanguages.kt from a checkout of
https://github.com/LuteOrg/lute-language-defs (definition.yaml + story .txt files).

Usage: python3 tools/generate_language_defs.py <lute-language-defs dir>
"""
import glob
import os
import re
import sys

import yaml

OUT = "core/domain/src/commonMain/kotlin/com/tayra/languages/core/domain/language/PredefinedLanguages.kt"


def kstr(s):
    """Kotlin raw string literal."""
    s = s.replace("$", "${'$'}")
    s = s.replace('"""', '\\"\\"\\"')
    return '"""' + s + '"""'


def qstr(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"').replace("$", "\\$").replace("\n", "\\n") + '"'


def load_stories(directory):
    stories = []
    for filename in sorted(glob.glob(os.path.join(directory, "*.txt"))):
        with open(filename, encoding="utf-8") as f:
            content = f.read()
        title = re.search(r"title:\s*(.*)\n", content).group(1).strip()
        source = None
        m = re.search(r"source_url:(.*)\n", content)
        if m and m.group(1).strip():
            source = m.group(1).strip()
        content = re.sub(r"#.*\n", "", content).strip()
        stories.append((title, source, content))
    return stories


def main(root):
    defs = []
    for def_file in sorted(glob.glob(os.path.join(root, "*", "definition.yaml"))):
        directory = os.path.dirname(def_file)
        with open(def_file, encoding="utf-8") as f:
            d = yaml.safe_load(f)
        defs.append((d, load_stories(directory)))

    lines = []
    lines.append("package com.tayra.languages.core.domain.language")
    lines.append("")
    lines.append("import com.tayra.languages.core.domain.model.DictionaryType")
    lines.append("import com.tayra.languages.core.domain.model.DictionaryUse")
    lines.append("import com.tayra.languages.core.domain.model.Language")
    lines.append("import com.tayra.languages.core.domain.model.LanguageDictionary")
    lines.append("")
    lines.append("// Generated by tools/generate_language_defs.py from https://github.com/LuteOrg/lute-language-defs")
    lines.append("// Do not edit by hand.")
    lines.append("@Suppress(\"LargeClass\", \"MaxLineLength\")")
    lines.append("object PredefinedLanguages {")
    lines.append("")
    names = []
    for d, stories in defs:
        name = d["name"]
        ident = re.sub(r"[^A-Za-z0-9]", "", name)
        names.append(ident)
        lines.append(f"    private fun {ident[0].lower() + ident[1:]}() = LanguageDefinition(")
        lines.append("        language = Language(")
        lines.append(f"            name = {qstr(name)},")
        lines.append("            dictionaries = listOf(")
        for i, dd in enumerate(d.get("dictionaries") or []):
            use = "DictionaryUse.TERMS" if dd["for"] == "terms" else "DictionaryUse.SENTENCES"
            typ = "DictionaryType.EMBEDDED" if dd["type"] == "embedded" else "DictionaryType.POPUP"
            active = "true" if dd.get("active", True) else "false"
            lines.append(f"                LanguageDictionary(useFor = {use}, type = {typ}, url = {qstr(str(dd['url']).strip())}, isActive = {active}, sortOrder = {i + 1}),")
        lines.append("            ),")
        def opt(key, kname, is_str=True):
            if key in d and d[key] is not None:
                v = d[key]
                if isinstance(v, bool):
                    lines.append(f"            {kname} = {'true' if v else 'false'},")
                elif isinstance(v, str) and v.strip().lower() in ("true", "false"):
                    lines.append(f"            {kname} = {v.strip().lower()},")
                else:
                    lines.append(f"            {kname} = {qstr(str(v))},")
        opt("character_substitutions", "characterSubstitutions")
        opt("split_sentences", "regexpSplitSentences")
        opt("split_sentence_exceptions", "exceptionsSplitSentences")
        opt("word_chars", "wordCharacters")
        opt("right_to_left", "rightToLeft")
        opt("show_romanization", "showRomanization")
        opt("parser_type", "parserType")
        lines.append("        ),")
        lines.append("        stories = listOf(")
        for title, source, text in stories:
            src = qstr(source) if source else "null"
            lines.append(f"            StoryDefinition(title = {qstr(title)}, sourceUrl = {src}, text = {kstr(text)}),")
        lines.append("        ),")
        lines.append("    )")
        lines.append("")
    lines.append("    val all: List<LanguageDefinition> by lazy {")
    lines.append("        listOf(")
    for ident in names:
        lines.append(f"            {ident[0].lower() + ident[1:]}(),")
    lines.append("        )")
    lines.append("    }")
    lines.append("}")
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    print(f"wrote {OUT}: {len(defs)} languages")


if __name__ == "__main__":
    main(sys.argv[1])
